stages:
  - build
  - deploy

variables:
  TARGET_DIR: "/var/www/wirvsvirus"

composer install:
  only:
    - master
    - 3-deploy-auf-den-server
  image: php:7.2
  stage: build
  before_script:
    - apt-get update -qq -o Dpkg::Use-Pty=0
    - apt-get install -qq -y -o Dpkg::Use-Pty=0 git
    - curl -sS https://getcomposer.org/installer | php
  script:
    - ./composer.phar install --no-dev --optimize-autoloader
  artifacts:
    untracked: true
    paths:
      - vendor/

Deploy Staging:
  environment:
    name: Staging
    url: https://wirvsvirus.marvin-naumann.de
  tags:
    - staging-runner
  only:
    - master
    - 3-deploy-auf-den-server
  stage: deploy
  dependencies:
    - composer install
  script:
    - cp -a bin/ $TARGET_DIR
    - cp -a config/ $TARGET_DIR
    - cp -a public/ $TARGET_DIR
    - cp -a src/ $TARGET_DIR
    - cp -a templates/ $TARGET_DIR
    - cp -a vendor/ $TARGET_DIR
    - php7.2 bin/console cache:clear
    - php7.2 bin/console doctrine:migrations:migrate