#index:
#    path: /
#    controller: App\Controller\DefaultController::index
locales:
    type:     rest
    prefix:   /api
    resource: App\Controller\LocaleController

countries:
    type:     rest
    prefix:   /api
    resource: App\Controller\CountryController
