@startuml

hide empty fields
hide empty methods

class Locale {
    + id
    + iso
}

class Area {
    + id
    + code
    + parent_area
}

Area }-- Area

class AreaTranslation {
    + id
    + area_id
    + locale_id
    + name
}

AreaTranslation }-- Area
AreaTranslation }-- Locale

class DataSource {
    + id
    + url
}

class DataSourceTranslation {
    + id
    + data_source_id
    + locale_id
    + name
}

DataSourceTranslation }-- DataSource
DataSourceTranslation }-- Locale

class Limitation {
    + id
    + area_id
    + valid_since
    + valid_until
}

Limitation }-- Area

class LimitationTranslation {
    + id
    + limitation_id
    + locale_id
    + title
    + description
    + data_source_id
    + data_source_url
}

LimitationTranslation }-- Limitation
LimitationTranslation }-- Locale
LimitationTranslation }-- DataSource

@enduml
