@startuml

@hide empty fields
@hide empty methods

class Locale {
    + id
    + iso
}

class Area {
    + id
    + code
    + parent_area
}

Area }-- Area

class AreaTranslation {
    + id
    + area_id
    + locale_id
    + name
}

AreaTranslation }-- Area
AreaTranslation }-- Locale

class DataSource {
    + id
    + url
}

class DataSourceTranslation {
    + id
    + data_source_id
    + locale_id
    + name
}

DataSourceTranslation }-- DataSource
DataSourceTranslation }-- Locale

@enduml
